name: Build, test, and doc update
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up OCaml"
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "ocaml-base-compiler.5.0.0~alpha0"
          cache-prefix: ${{ inputs.cache-prefix }}
          opam-repositories: |
            default: https://opam.ocaml.org
            alpha: git+https://github.com/kit-ty-kate/opam-alpha-repository.git
      - name: "Install the dependencies"
        shell: sh
        run: opam install --with-test ${{inputs.with-doc == 'true' && '--with-doc' || ''}} --deps-only --yes --verbose .
      - name: "Build the package"
        shell: sh
        run: opam exec -- dune build
      - name: "Test the package"
        shell: sh
        run: opam exec -- dune runtest
      - name: "Build the documentation"
        if: ${{ inputs.with-doc == 'true' }}
        shell: sh
        run: opam exec -- dune build @doc
      - name: "Publish the documentation"
        if: ${{ inputs.with-doc == 'true' && inputs.publish-doc-if-built == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ inputs.github-token }}
          publish_dir: "./_build/default/_doc/_html/"
